# Generated by Django 2.0.7 on 2018-07-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('type', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='postalCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='province',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='siteNbr',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='telephone',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='town',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='website',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='hospital_siteNbr',
            field=models.ForeignKey(db_column='hospital_siteNbr', on_delete=django.db.models.deletion.CASCADE, to='api.Hospital', to_field='siteNbr'),
        ),
    ]
