# Generated by Django 2.0.7 on 2018-07-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospitals',
            new_name='Hospital',
        ),
    ]
