# Generated by Django 2.0.7 on 2018-07-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_population'),
    ]

    operations = [
        migrations.RenameField(
            model_name='population',
            old_name='province',
            new_name='name',
        ),
    ]
