# Generated by Django 2.0.7 on 2018-07-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180717_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationDetailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('year', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=600, null=True)),
            ],
        ),
    ]
