# Generated by Django 2.0.7 on 2018-07-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_populationdetailed'),
        ('api', '0002_auto_20180717_1254'),
    ]

    operations = [
    ]
