# Generated by Django 2.0.7 on 2018-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_populationdetailed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=500)),
                ('agegroup', models.CharField(max_length=500)),
                ('crude', models.IntegerField()),
                ('province', models.CharField(max_length=500)),
            ],
        ),
    ]
