# Generated by Django 2.0.7 on 2018-07-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_populationdetailed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agegroup', models.CharField(max_length=600)),
                ('gender', models.CharField(max_length=600)),
                ('region', models.CharField(max_length=600)),
                ('cancer', models.CharField(max_length=600)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
