# Generated by Django 2.0.7 on 2018-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_populationdetailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationdetailed',
            name='code',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
