# Generated by Django 2.0.7 on 2018-07-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancer',
            name='value',
            field=models.CharField(max_length=600),
        ),
    ]
