# Generated by Django 2.0.7 on 2018-07-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20180719_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='type',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
