# Generated by Django 2.0.7 on 2018-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_depression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depression',
            name='crude',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
