# Generated by Django 2.0.7 on 2018-07-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180718_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='depression',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
