# Generated by Django 2.0.7 on 2018-07-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_depression_year'),
        ('api', '0005_populationdetailed_code'),
        ('api', '0002_auto_20180717_1254'),
    ]

    operations = [
    ]
