# Generated by Django 2.0.7 on 2018-07-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20180723_0613'),
        ('api', '0006_auto_20180719_2243'),
    ]

    operations = [
    ]
