# Generated by Django 2.0.7 on 2018-07-19 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180719_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='hospital_siteNbr',
        ),
        migrations.AddField(
            model_name='bed',
            name='network',
            field=models.ForeignKey(db_column='network_id', default='', on_delete=django.db.models.deletion.CASCADE, to='api.HospitalNetwork'),
            preserve_default=False,
        ),
    ]
