# Generated by Django 2.0.7 on 2018-07-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180719_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='siteNbr',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
