# Generated by Django 2.0.7 on 2018-07-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180719_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='typeName',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
