# Generated by Django 2.0.7 on 2018-07-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_populationdetailed_code'),
        ('api', '0013_merge_20180723_0744'),
    ]

    operations = [
    ]
