# Generated by Django 2.0.7 on 2018-07-23 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20180723_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('code', models.CharField(max_length=5, unique=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='department',
            field=models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='api.Department', to_field='code'),
        ),
    ]
