# Generated by Django 2.0.7 on 2018-07-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20180723_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationdetailed',
            name='code',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
