# Generated by Django 2.0.7 on 2018-07-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180723_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='type',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='typeName',
        ),
    ]
