# Generated by Django 2.0.7 on 2018-07-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180724_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Population',
        ),
    ]
