# Generated by Django 2.0.7 on 2018-07-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180724_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('year', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=600, null=True)),
                ('code', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PopulationDetailed',
        ),
    ]
